### ISSUE TITLE
Remove `stale.yml`?

### ISSUE THREAD

**Issue by Marcono1234** [github/github-ospo#10]
This project has currently a `stale.yml` file, however it appears probot-stale is not actively maintained anymore, see https://github.com/probot/stale/issues/385.

Though in general, all these stale bots can be disruptive for contributors (see for example https://github.com/actions/stale/issues/719 and linked issues and discussions), so maybe unless you really find yourself in a situation where there are too many outdated issues / pull requests in the future, would it make sense to remove the stale bot?

**Comment by ljharb** [comment]
Also, stalebots are highly controversial. Perhaps it's best *not* to include it in an endorsed Github OSPO template? I doubt incurring that controversy is going to make it easier for a company to get internal buyin for its OSPO.

**Comment by zkoppert** [comment]
Thanks both for the input. I do use stalebot on a lot of things personally and this just got carried over and forgotten. I'll remove it. No need to have stalebot in here.

**Comment by zkoppert** [comment]
68f7d2cd663d8753f7770376c11287438bd672ab
