### ISSUE TITLE
Only release automatically on Major, minor, or vuln fix PRs

### ISSUE THREAD

**Issue by zkoppert** [github/github-ospo#105]
### Is your feature request related to a problem?

Yes, Currently our automated release process on actions releases after every merge to main. This could create more noise than necessary. For example if its only a documentation related update or dependabot PR than we don't really need to create a release for that.

### Related OSPO Tool

automatic-contrib-prs GitHub Action, cleanowners GitHub Action, contributors GitHub Action, evergreen GitHub Action, internal-contribution-forks GitHub App, issues-metrics GitHub Action, stale-repos GitHub Action

### Describe the solution you'd like

We should only create a release for major, minor, and vulnerability fixes.

**Comment by jmeridth** [comment]
Initial thought is label detection but not clear on how to detect labels on the last merge to main from GitHub Actions.  Still researching this.  We can either always do the release and then mark `no-release` label on ones we don't want a release or vice-versa, add `release` label for when we want the automated release to fire.  Can even auto label with `release` when it is CVE/Security or major/minor related. 🤔

**Comment by zkoppert** [comment]
Looks great!!

**Comment by jmeridth** [comment]
I'm not finding a way to detect the last pull request's labels when a merge to the default branch occurs.  May have to rethink our release workflow 🤔

**Comment by zkoppert** [comment]
Wohoo!
