### ISSUE TITLE
Migrate from branch protection to ruleset for OSPO GitHub Actions and App

### ISSUE THREAD

**Issue by jmeridth** [github/github-ospo#108]
### Is your feature request related to a problem?

Not really.  The [OSSF GitHub Action Issue](https://github.com/github/github-ospo/issues/84) states if we [use a ruleset instead of a branch protection we can use the base/given `GH_TOKEN` instead of a custom PAT that needs additional permissions](dependency-review-action).

We should also use GitHub's newer tooling on our repositories to be an example of usage.

### Related OSPO Tool

- [x] automatic-contrib-prs GitHub Action
- [x] cleanowners GitHub Action
- [x] contributors GitHub Action
- [x] evergreen GitHub Action
- [x] internal-contribution-forks GitHub App
- [x] issues-metrics GitHub Action
- [x] stale-repos GitHub Action

### Describe the solution you'd like

Migrate from branch protection rule to ruleset

We will want the permissions to initially match 1 to 1.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by zkoppert** [comment]
> we can use the base/given GH_TOKEN instead of a custom PAT 

Oh cool!

**Comment by jmeridth** [comment]
@ajhenry will need your help on ICF to do this since I don't have permissions.

**Comment by jmeridth** [comment]
This has been completed.
