### ISSUE TITLE
CLA vs. implicit agreement through GitHub Terms of Service

### ISSUE THREAD

**Issue by Marcono1234** [github/github-ospo#14]
The page about Contributor License Agreement (CLA) (`contributor-license-agreements.md`) currently says:
> Not all projects will require a CLA but should one be required to contribute to a project ...

Maybe in this context it would be useful to refer to GitHub's Terms of Service [which say](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license):
> Whenever you add Content to a repository containing notice of a license, you license that Content under the same terms, and you agree that you have the right to license that Content under those terms. If you have a separate agreement to license that Content under different terms, such as a contributor license agreement, that agreement will supersede.
> 
> Isn't this just how it works already? Yep. This is widely accepted as the norm in the open-source community; it's commonly referred to by the shorthand "inbound=outbound". We're just making it explicit.

(note sure though how many users are actually aware of this)

Arguably CLAs are a somewhat controversial topic though. Using your favorite search engine to search for advantages and disadvantages should bring up multiple articles and blog posts.
Maybe it would be useful if this repository could provide more information on the topic of CLAs if that is possible, or link to third party sites where advantages and disadvantages are compared (if there is a comprehensive and up-to-date site).

**Comment by zkoppert** [comment]
more context on this for my own reference: https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/

**Comment by zkoppert** [comment]
What I'd like to do from a vision standpoint is keep this in line with GitHub's own policy. I'll look to add some clarity to this section and update here.
