### ISSUE TITLE
Placeholder issue for image uploading

### ISSUE THREAD

**Issue by ahpook** [github/github-ospo#57]
With the new JWT-protected images on githubusercontent, it's easy to host an image by creating an issue in the same repo and dropping it in there to get a persistent URL.

**Comment by ahpook** [comment]
It also makes a handy markdown line for the image, which syntax I can _never_ remember

![A Grafana dashboard of GitHub repository statistics for the cli/cli repo](https://github.com/github/github-ospo/assets/56753/b8f22a07-d581-4b58-b621-0959eefa39e2)

**Comment by ahpook** [comment]
![Cauldron.io Performance graphs for an open source project showing time to resolution for issues and PRs](https://github.com/github/github-ospo/assets/56753/5a8fa8f6-a6a5-49aa-a982-d80ee44b2e1d)

**Comment by zkoppert** [comment]
@ahpook okay to close this one?

**Comment by ahpook** [comment]
@zkoppert yep. i'll probably continue to use it for images but no need for it to stay open.
