### ISSUE TITLE
Fix typos in Contributor License Agreements

### ISSUE THREAD

**Issue by ChVeen** [github/github-ospo#7]
In file `policies/contributor-license-agreements.md` are typos:

"[...] Not all projects will **reqiuire** a CLA but **should a one** be required to [...]"

should be

"[...] Not all projects will **require** a CLA but **should one** be required to [...]"

**Comment by ChVeen** [comment]
Since in the `README.md` file only issues are mentioned and not pull requests, I did not fix it on my own.

**Comment by zkoppert** [comment]
Thanks for the issue! I've opened a PR for that and I will also change the REAMDE to let folks know its okay to open a PR.
