### ISSUE TITLE
Update actions readmes/contributing to point back to github-ospo

### ISSUE THREAD

**Issue by ahpook** [github/github-ospo#75]
Currently the various ospo actions are completely separate and there's not much connective "tissue" between them and the broader efforts to help OSPOs on GitHub. As a first step, we should update their READMEs to headline the rest of the tools and the github/github-ospo repo, plus indicate that PRs about the code in a specific action lives in its repo, but questions about overall usage or feature enhancements should go here instead. The actions are in:

* github/automatic-contrib-prs
* github/cleanowners
* github/contributors
* github/evergreen
* github/issue-metrics
* github/stale-repos

**Comment by jmeridth** [comment]
@ahpook 

Love the link back to this repo (helps inform users there are other GitHub Actions available)

I'm wary of the Issues being back on this repo for all the Actions.  Is this for ease of centralization for product and to ensure we keep each repo in "sync" (shared techniques, etc)?  I assume so.

This is not the norm for open-source contributation IMO.  I'd done something else.  I've created a project at the organization level (e.g., OSPO) and when issues are created in each repository we can automate assigning them to that project.  Therefore product and maintainers get one location to manage issues.  Still gives contributors the "normal" open-source process "feel" but allows product/maintainers to not have to go to each repository.  Especially as the repository count grows.

wdyt?

**Comment by jmeridth** [comment]
Looks like [there is already have a project](https://github.com/orgs/github/projects/12731/views/1) 😄 @ahpook is way ahead of me.

**Comment by ahpook** [comment]
I'm just getting things set up 👍 but yeah, my thought was that the board should live in github-ospo, along with any issues that are "meta" questions like the ones about unifying config files, requests for new actions etc. But issues related to a specific action should clearly stay in that action's repo.

**Comment by jmeridth** [comment]
@ahpook What verbiage would you want in the README's for each project so they point back to github.com/github/github-ospo?

Something like:

```md
## Issues and PRs

All feedback regarding our GitHub Actions, as a whole, should be communicated through
[issues on our github-ospo repository](https://github.com/github/github-ospo/issues).

Issues and Pull Requests specific to this GitHub Action should be filed on this repository.
```

**Comment by lelia** [comment]
From my POV that phrasing seems fine. My only note would be that perhaps it's worth adding an Issue Template in support of this type of feedback on [github-ospo](https://github.com/github/github-ospo/issues/new).

**Comment by jmeridth** [comment]
@ahpook I believe this one is complete.  All GitHub Actions READMEs have been updated to point back to this repository for overall issues.

**Comment by ahpook** [comment]
LGTM! Thanks JM

**Comment by VianSanjaya** [comment]
[csv-writer-master.zip](https://github.com/github/github-ospo/files/14968946/csv-writer-master.zip)
