### ISSUE TITLE
Automate release process for ospo-actions

### ISSUE THREAD

**Issue by ahpook** [github/github-ospo#78]
Current:

- PR is created
- Maintainer labels PR so it gets categorized for release
- PR is reviewed, approved and merged into base branch
- GitHub Action creates release draft
- Maintainer validates draft and publishes release (and added to discussion Announcements)
- Maintainer locally creates GitHub Action image, tags it (latest, vX, vX.X.X) and pushes it to ghcr.io

Desired:

- PR is created
- GitHub Action to validate label present fails
- Maintainer labels PR so it gets categorized in release
- GitHub Action to validate label present passes
- PR is reviewed, approved and merged into base branch
- Release automatically created (and added to discussion Announcements)
- GitHub Action container image created, tagged (latest, vX, vX.X.X) and pushed to ghcr.io

**Comment by jmeridth** [comment]
@zkoppert/@ahpook before I fill out the description above, __does this issue mean we will automate releases when PRs merge or is release management still manual__?  If automated, I'd like to introduce an issue and pull request to require PRs have labels so that they are categorized in the release.  If we automate and don't do that, then some PRs will be uncategorized (accidentally).

If this is just about automating the Action container images and releases are still manual, then I can write the description up that way.

Both paths I will summarize the GitHub Action I plan to create to handle the image creation and pushing after a release.

Thank you.

**Comment by zkoppert** [comment]
Personally, I'd prefer it to be fully automated meaning automate a release each time a PR is merged to main. Requiring one of the labels in our set of supported labels would be great!

**Comment by jmeridth** [comment]
> Personally, I'd prefer it to be fully automated meaning automate a release each time a PR is merged to main. Requiring one of the labels in our set of supported labels would be great!

Awesome.  Thank you.  Will get description updated and ask for feedback.

**Comment by jmeridth** [comment]
Thinking about this more last night, I'd very much be a fan of using the `amannn/action-semantic-pull-request` GitHub action to force PR titles (adhering to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#specification)), this GHA uses the `conventional-commit-types` npm package that has the [following prefixes available](https://github.com/commitizen/conventional-commit-types/blob/master/index.json)

- feat
- fix
- docs
- style
- refactor
- perf
- test
- build
- ci
- chore
- revert

We can then use the [Auto Labeler feature](https://github.com/release-drafter/release-drafter?tab=readme-ov-file#autolabeler) of the pre-releaser GHA to use regex based on the PR prefixes to auto label the PRs.

A side benefit is that, as a maintainer, you can look at the repo's pull requests and easily see what type they are based on the prefix and the auto labelling.

Full disclosure: we use this for argo-helm in the argoproj org.  It works well.  There can be a little frustration by first-time contributors on how to get the titles correct, but our error messaging gave clarity to help them.

**Comment by zkoppert** [comment]
If we are adding friction for first time contributors lets just make sure we spell everything out in our contributing docs and continue to be responsive in issues and PRs. Sounds like a great plan!

**Comment by lumaxis** [comment]
A nice aspect of PR titles imo is that they can also be adjusted by maintainers of a repo i.e. us, so we can help/"just fix it" for contributors if they get it wrong and don't necessarily have to go through a back and forth cycle with them.

**Comment by lelia** [comment]
> If we are adding friction for first time contributors lets just make sure we spell everything out in our contributing docs and continue to be responsive in issues and PRs. Sounds like a great plan!

+1 to this take. I'm a big fan of keeping things labeled / organized, but those standards will need to be clearly articulated in the docs and perhaps some hints added to the PR / Issue templates directly, in case contributors skip the README / CONTRIBUTORS.md 🙂

**Comment by jmeridth** [comment]
Automated Releases for the OSPO GitHub Actions:

- [x] https://github.com/github/automatic-contrib-prs/pull/55
- [x] https://github.com/github/cleanowners/pull/52
- [x] https://github.com/github/contributors/pull/92
- [ ] https://github.com/github/evergreen/pull/99
- [x] https://github.com/github/issue-metrics/pull/242
- [x] https://github.com/github/stale-repos/pull/118

**Comment by jmeridth** [comment]
This is complete
