### ISSUE TITLE
Add issue template for reporting issues for this project

### ISSUE THREAD

**Issue by Marcono1234** [github/github-ospo#9]
It appears currently the existing GitHub issue templates of this project are intended for the actual open source projects themselves:
![Issue type selection](https://user-images.githubusercontent.com/11685886/225126295-96fc6f1d-cf55-4d1d-bf39-cc671bc0122d.png)

However, if you just want to report something against this project here (github-ospo), these templates are quite irritating. Would it make sense to have an additional issue template to report issues against github-ospo, or remove the existing templates (or move them to a separate folder) if they are not actually applicable directly here?

**Comment by zkoppert** [comment]
Thanks for bringing this up. Removed these here: ec9f01fcd327237e0acc8d19c8eb099f3856324f
